### ISSUE TITLE
!npをしたときに次に再生される曲が表示される

### ISSUE THREAD

**Issue by SehataKuro** [SehataKuro/seibaribot#60]
キューに次の曲が追加されている状態で!npをすると次の曲のほうの情報が表示されます。

**Comment by naari3** [comment]
`!np` は `Music` 内の `self.palyer` の情報を取得しているのだが
https://github.com/SehataKuro/seibaribot/blob/c3ea25058b38616c4b4afd285a3623140348395e/discordbot.py#L138

`!play` ではqueueに追加する場合であっても `self.player` に代入しているため、っぽく見えた
https://github.com/SehataKuro/seibaribot/blob/c3ea25058b38616c4b4afd285a3623140348395e/discordbot.py#L111

ので、この問題は実際には「`!play` によって最後に追加した曲が `!np` によって表示される」のように思えます！

対処するのであれば `self.player` に代入するタイミングを変える必要があるかも。キューに追加する時は `self.player` を変える必要ないですよね　多分
